-- 회원 시퀀스
DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ;

-- 공지사항 시퀀스
DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ;

-- 예약 시퀀스
DROP SEQUENCE RESERVATION_SEQ;
CREATE SEQUENCE RESERVATION_SEQ;


-- 회원정보
-- 제약조건이 있는 테이블일 경우 DROP시 CASECADE CONSTRAINTS 옵션을 사용
DROP TABLE TB_COM_USER CASCADE CONSTRAINT;
CREATE TABLE TB_COM_USER(
  USER_CODE VARCHAR2(20),             -- 유저코드
  ID VARCHAR2(20),                    -- 아이디
  PW VARCHAR2(20),                    -- 패스워드
  NAME VARCHAR2(20),                  -- 이름
  GRADE VARCHAR2(1) DEFAULT 'M',	  -- 회원등급
  CONSTRAINT TB_COM_USER_PK PRIMARY KEY(USER_CODE)
);

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, NAME, GRADE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, '관리자', '123', '관리자', 'A');

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, NAME, GRADE) 
VALUES ('USER0000' || USER_SEQ.NEXTVAL, 'asd', 'asd', '바다', 'M');

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, NAME, GRADE) 
VALUES ('USER0001' || USER_SEQ.NEXTVAL, 'bsd', 'bsd', '하늘', 'M');

commit;


-- 공지사항 정보
-- 제약조건이 있는 테이블일 경우 DROP시 CASECADE CONSTRAINTS 옵션을 사용
DROP TABLE TB_NOTICE CASCADE CONSTRAINT;
CREATE TABLE TB_NOTICE(
  NTC_NO VARCHAR2(20),   	      	  -- 글번호
  NTC_TITLE VARCHAR2(50) NOT NULL,    -- 제목
  NTC_CONTENT VARCHAR2(4000), 	 	  -- 내용
  NTC_REG_ID VARCHAR2(20),    	 	  -- 등록자(수정자와 동일)
  NTC_REG_DATE VARCHAR2(20),  	 	  -- 등록일자
  CONSTRAINT TB_NOTICE_PK PRIMARY KEY(NTC_NO)
);



-- 예약 정보 1
-- 제약조건이 있는 테이블일 경우 DROP시 CASECADE CONSTRAINTS 옵션을 사용
DROP TABLE TB_RESERVATION CASCADE CONSTRAINT;                            
CREATE TABLE TB_RESERVATION(
  RES_NO VARCHAR2(20),            	  -- 글번호
  RES_REG_ID VARCHAR2(20),   	      -- 등록자
  RES_DATE VARCHAR2(20)NOT NULL,			-- 예약일자
  RES_TIME VARCHAR2(20),			-- 예약시간
  RES_PERSONNEL VARCHAR2(20)NOT NULL,		-- 관람인원
  RES_REG_DATE VARCHAR2(20),  	 	  -- 등록일자
  CONSTRAINT TB_RESERVE_PK PRIMARY KEY(RES_NO)
);

commit;